apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-service
  template:
    metadata:
      labels:
        app: greeting-service
    spec:
      containers:
      - name: greeting-service
        image: greeting-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
spec:
  selector:
    app: greeting-service
  ports:
  - port: 6000
    targetPort: 6000
  type: NodePort
